name: Locust Performance Tests

on:
  push:
    branches: [ main ]

jobs:
  locust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Locust
        run: pip install locust

      - name: Run Locust Tests
        run: locust --host http://localhost:8080
